# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  hava-cli-demo:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: hava/cli:latest
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "hava version"
          command: "hava -v"
      - run:
          name: "List Hava sources"
          command: "hava source list"
      - name: 
          name: Create Source AWS (Using Access Keys)
          command: hava  source create aws --name $HAVA_AWS_SOURCE_NAME --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
      - run:
          name: List ALL sources
          command: hava  source list

      - run:
          name: Create Source AWS (Using Cross Account Roles)
          command: hava  source create aws --name $HAVA_AWSCAR_SOURCE_NAME --role-arn $AWS_CROSS_ACCOUNT_ROLE

      - run:
          name: Create Source GCP
          command: hava  source create gcp  --name $HAVA_GCP_SOURCE_NAME --config-file $GCP_ENCODED_FILE

      - run:
          name: Create Source Azure
          command: hava  source create azure --name $HAVA_AZURE_SOURCE_NAME --client-id $ARM_CLIENT_ID --tenant-id $ARM_TENANT_ID --subscription-id $ARM_SUBSCRIPTION_ID --secret-key $ARM_SECRET_TEXT

      - run:
          name: List ALL sources
          command: hava  source list

      - run:
          name: List ALL sources (JSON OUTPUT)
          command: hava  source list --json

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  hava-cli-demo-workflow:
    jobs:
      - hava-cli-demo
