name: test flow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    env:
      APPLE_USERNANME: ${{ secrets.APPLE_USERNANME }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4

      - 
        name: Install gon
        run: |
          go env
          export GOPATH=$(go env GOPATH)
          echo "gopath: ${GOPATH}/bin"
          echo "path: ${PATH}"
          ls $(go env GOPATH)
          ls $(go env GOPATH)/bin
          go get github.com/mitchellh/gon 
          go install github.com/mitchellh/gon
          ls $(go env GOPATH)/bin
          gon -v
