name: Build `hava` - Cross Compile

on:
  push:
    branches:
      - main
    paths:
    - cmd/**
    - havaclient/**.go
    - printer/**.go
    - version/**.go
  pull_request:
    branches:
      - main
    paths:
    - cmd/**
    - havaclient/**.go
    - printer/**.go
    - version/**.go
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
      - name: Install gox
        run: |
          go get github.com/mitchellh/gox 
          go install github.com/mitchellh/gox 
      - name: Install zip
        run: |
          sudo apt-get update -q
          sudo apt-get install zip -q

      - name: Cross compile
        run: |
          gox \
            -os="linux darwin windows" \
            -ldflags="-X 'github.com/teamhava/hava-ui-cli/version.Build=${{ github.sha }}' -X 'github.com/teamhava/hava-ui-cli/version.Date=$(date)' -X 'github.com/teamhava/hava-ui-cli/version.BuiltBy=github'" \
            -arch="amd64 arm64" \
            -output "./pkg/{{.OS}}_{{.Arch}}/hava" \
            .
      - name: Print version
        run: ./pkg/linux_amd64/hava --version
        
      # Package all binaries together
      - uses: actions/upload-artifact@v3
        with:
          name: hava-artifacts
          path: ./pkg/*     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}