name: Hava binary release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    env:
      APPLE_USERNAME: ${{ secrets.APPLE_USERNAME }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4

      - 
        name: Install gon
        run: |
          curl -L -o gon.zip https://github.com/mitchellh/gon/releases/download/v0.2.5/gon_macos.zip
          unzip gon.zip
          rm gon.zip
          mv gon $(go env GOPATH)/bin/gon
          gon -v

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Sign binary with gon
        run: gon gon.hcl
